services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $dataDirectory: "%kimai.data_dir%"

    KimaiPlugin\ExtendedPunchIn\:
        resource: '../../*'
        exclude:
            - '../../Migrations/'
            - '../../Resources/'

#    KimaiPlugin\ExtendedPunchIn\Controller\:
#        resource: '../../Controller'
#        tags: ['controller.service_arguments']

#    KimaiPlugin\ExtendedPunchIn\EventSubscriber\ActionsSubscriber:
#        arguments:
#            $environment: '%kernel.environment%'
#            $photosDirectory: '%photos_directory%'

parameters:
    photos_directory: "%kimai.data_dir%/pictures/clockin"
